version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Building Maven project
      - mvn clean package

artifacts:
  files:
    - target/*.war
  discard-paths: yes
